#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! This file contains default values for the custom infrastructure provider.
#! These are the values that will be set if not overridden by the user.

#@overlay/match-child-defaults missing_ok=True
#@overlay/replace
clusterPackages:
  contour:
    enabled: false
    settings: {}
  cert-manager:
    enabled: false
    settings: {}
  external-dns:
    enabled: false
    settings: {}
  certs:
    enabled: false
    settings: {}
  kyverno:
    enabled: true
    settings: {}
  kapp-controller:
    enabled: false
    settings: {}
  educates:
    enabled: true
    settings: {}
  lookup-service:
    enabled: false
    settings: {}