//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEConfig) DeepCopyInto(out *ACMEConfig) {
	*out = *in
	in.Solvers.DeepCopyInto(&out.Solvers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEConfig.
func (in *ACMEConfig) DeepCopy() *ACMEConfig {
	if in == nil {
		return nil
	}
	out := new(ACMEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEDNS01Solver) DeepCopyInto(out *ACMEDNS01Solver) {
	*out = *in
	if in.Route53 != nil {
		in, out := &in.Route53, &out.Route53
		*out = new(Route53Config)
		**out = **in
	}
	if in.CloudDNS != nil {
		in, out := &in.CloudDNS, &out.CloudDNS
		*out = new(CloudDNSConfig)
		**out = **in
	}
	if in.Cloudflare != nil {
		in, out := &in.Cloudflare, &out.Cloudflare
		*out = new(CloudflareConfig)
		**out = **in
	}
	if in.AzureDNS != nil {
		in, out := &in.AzureDNS, &out.AzureDNS
		*out = new(AzureDNSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEDNS01Solver.
func (in *ACMEDNS01Solver) DeepCopy() *ACMEDNS01Solver {
	if in == nil {
		return nil
	}
	out := new(ACMEDNS01Solver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEHTTP01Solver) DeepCopyInto(out *ACMEHTTP01Solver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEHTTP01Solver.
func (in *ACMEHTTP01Solver) DeepCopy() *ACMEHTTP01Solver {
	if in == nil {
		return nil
	}
	out := new(ACMEHTTP01Solver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMESolvers) DeepCopyInto(out *ACMESolvers) {
	*out = *in
	in.DNS01.DeepCopyInto(&out.DNS01)
	if in.HTTP01 != nil {
		in, out := &in.HTTP01, &out.HTTP01
		*out = new(ACMEHTTP01Solver)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMESolvers.
func (in *ACMESolvers) DeepCopy() *ACMESolvers {
	if in == nil {
		return nil
	}
	out := new(ACMESolvers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDNSConfig) DeepCopyInto(out *AzureDNSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDNSConfig.
func (in *AzureDNSConfig) DeepCopy() *AzureDNSConfig {
	if in == nil {
		return nil
	}
	out := new(AzureDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundledCertManagerConfig) DeepCopyInto(out *BundledCertManagerConfig) {
	*out = *in
	if in.ACME != nil {
		in, out := &in.ACME, &out.ACME
		*out = new(ACMEConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomCA != nil {
		in, out := &in.CustomCA, &out.CustomCA
		*out = new(CustomCAConfig)
		**out = **in
	}
	if in.Operational != nil {
		in, out := &in.Operational, &out.Operational
		*out = new(OperationalBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundledCertManagerConfig.
func (in *BundledCertManagerConfig) DeepCopy() *BundledCertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(BundledCertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundledContourConfig) DeepCopyInto(out *BundledContourConfig) {
	*out = *in
	if in.Operational != nil {
		in, out := &in.Operational, &out.Operational
		*out = new(OperationalBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundledContourConfig.
func (in *BundledContourConfig) DeepCopy() *BundledContourConfig {
	if in == nil {
		return nil
	}
	out := new(BundledContourConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundledExternalDNSConfig) DeepCopyInto(out *BundledExternalDNSConfig) {
	*out = *in
	if in.Route53 != nil {
		in, out := &in.Route53, &out.Route53
		*out = new(ExternalDNSRoute53Config)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudDNS != nil {
		in, out := &in.CloudDNS, &out.CloudDNS
		*out = new(ExternalDNSCloudDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Operational != nil {
		in, out := &in.Operational, &out.Operational
		*out = new(OperationalBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundledExternalDNSConfig.
func (in *BundledExternalDNSConfig) DeepCopy() *BundledExternalDNSConfig {
	if in == nil {
		return nil
	}
	out := new(BundledExternalDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundledKyvernoConfig) DeepCopyInto(out *BundledKyvernoConfig) {
	*out = *in
	if in.Operational != nil {
		in, out := &in.Operational, &out.Operational
		*out = new(OperationalBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundledKyvernoConfig.
func (in *BundledKyvernoConfig) DeepCopy() *BundledKyvernoConfig {
	if in == nil {
		return nil
	}
	out := new(BundledKyvernoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificates) DeepCopyInto(out *Certificates) {
	*out = *in
	if in.BundledCertManager != nil {
		in, out := &in.BundledCertManager, &out.BundledCertManager
		*out = new(BundledCertManagerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalCertManager != nil {
		in, out := &in.ExternalCertManager, &out.ExternalCertManager
		*out = new(ExternalCertManagerConfig)
		**out = **in
	}
	if in.StaticCertificate != nil {
		in, out := &in.StaticCertificate, &out.StaticCertificate
		*out = new(StaticCertificateConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificates.
func (in *Certificates) DeepCopy() *Certificates {
	if in == nil {
		return nil
	}
	out := new(Certificates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConfig) DeepCopyInto(out *CloudConfig) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = new(CloudServiceAccounts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConfig.
func (in *CloudConfig) DeepCopy() *CloudConfig {
	if in == nil {
		return nil
	}
	out := new(CloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDNSConfig) DeepCopyInto(out *CloudDNSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDNSConfig.
func (in *CloudDNSConfig) DeepCopy() *CloudDNSConfig {
	if in == nil {
		return nil
	}
	out := new(CloudDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudServiceAccounts) DeepCopyInto(out *CloudServiceAccounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudServiceAccounts.
func (in *CloudServiceAccounts) DeepCopy() *CloudServiceAccounts {
	if in == nil {
		return nil
	}
	out := new(CloudServiceAccounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareConfig) DeepCopyInto(out *CloudflareConfig) {
	*out = *in
	out.APITokenSecretRef = in.APITokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareConfig.
func (in *CloudflareConfig) DeepCopy() *CloudflareConfig {
	if in == nil {
		return nil
	}
	out := new(CloudflareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyConfig) DeepCopyInto(out *ClusterPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyConfig.
func (in *ClusterPolicyConfig) DeepCopy() *ClusterPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCAConfig) DeepCopyInto(out *CustomCAConfig) {
	*out = *in
	out.CACertificateRef = in.CACertificateRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCAConfig.
func (in *CustomCAConfig) DeepCopy() *CustomCAConfig {
	if in == nil {
		return nil
	}
	out := new(CustomCAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
	if in.BundledExternalDNS != nil {
		in, out := &in.BundledExternalDNS, &out.BundledExternalDNS
		*out = new(BundledExternalDNSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EducatesClusterConfig) DeepCopyInto(out *EducatesClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EducatesClusterConfig.
func (in *EducatesClusterConfig) DeepCopy() *EducatesClusterConfig {
	if in == nil {
		return nil
	}
	out := new(EducatesClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EducatesClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EducatesClusterConfigList) DeepCopyInto(out *EducatesClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EducatesClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EducatesClusterConfigList.
func (in *EducatesClusterConfigList) DeepCopy() *EducatesClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(EducatesClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EducatesClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EducatesClusterConfigSpec) DeepCopyInto(out *EducatesClusterConfigSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(Infrastructure)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(Ingress)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNS)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyEnforcement != nil {
		in, out := &in.PolicyEnforcement, &out.PolicyEnforcement
		*out = new(PolicyEnforcement)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageRegistry != nil {
		in, out := &in.ImageRegistry, &out.ImageRegistry
		*out = new(ImageRegistry)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(InlineConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EducatesClusterConfigSpec.
func (in *EducatesClusterConfigSpec) DeepCopy() *EducatesClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EducatesClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EducatesClusterConfigStatus) DeepCopyInto(out *EducatesClusterConfigStatus) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(StatusIngress)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyEnforcement != nil {
		in, out := &in.PolicyEnforcement, &out.PolicyEnforcement
		*out = new(StatusPolicyEnforcement)
		**out = **in
	}
	if in.ImageRegistry != nil {
		in, out := &in.ImageRegistry, &out.ImageRegistry
		*out = new(ImageRegistry)
		(*in).DeepCopyInto(*out)
	}
	if in.BundledChartVersions != nil {
		in, out := &in.BundledChartVersions, &out.BundledChartVersions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EducatesClusterConfigStatus.
func (in *EducatesClusterConfigStatus) DeepCopy() *EducatesClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EducatesClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalCertManagerConfig) DeepCopyInto(out *ExternalCertManagerConfig) {
	*out = *in
	out.ClusterIssuerRef = in.ClusterIssuerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalCertManagerConfig.
func (in *ExternalCertManagerConfig) DeepCopy() *ExternalCertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalCertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSCloudDNSConfig) DeepCopyInto(out *ExternalDNSCloudDNSConfig) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSCloudDNSConfig.
func (in *ExternalDNSCloudDNSConfig) DeepCopy() *ExternalDNSCloudDNSConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSCloudDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSRoute53Config) DeepCopyInto(out *ExternalDNSRoute53Config) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSRoute53Config.
func (in *ExternalDNSRoute53Config) DeepCopy() *ExternalDNSRoute53Config {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSRoute53Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRegistry) DeepCopyInto(out *ImageRegistry) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRegistry.
func (in *ImageRegistry) DeepCopy() *ImageRegistry {
	if in == nil {
		return nil
	}
	out := new(ImageRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Infrastructure) DeepCopyInto(out *Infrastructure) {
	*out = *in
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CloudConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Infrastructure.
func (in *Infrastructure) DeepCopy() *Infrastructure {
	if in == nil {
		return nil
	}
	out := new(Infrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
	in.Certificates.DeepCopyInto(&out.Certificates)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressController) DeepCopyInto(out *IngressController) {
	*out = *in
	if in.BundledContour != nil {
		in, out := &in.BundledContour, &out.BundledContour
		*out = new(BundledContourConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressController.
func (in *IngressController) DeepCopy() *IngressController {
	if in == nil {
		return nil
	}
	out := new(IngressController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineConfig) DeepCopyInto(out *InlineConfig) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	out.PolicyEnforcement = in.PolicyEnforcement
	if in.ImageRegistry != nil {
		in, out := &in.ImageRegistry, &out.ImageRegistry
		*out = new(ImageRegistry)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineConfig.
func (in *InlineConfig) DeepCopy() *InlineConfig {
	if in == nil {
		return nil
	}
	out := new(InlineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineIngress) DeepCopyInto(out *InlineIngress) {
	*out = *in
	out.WildcardCertificateSecretRef = in.WildcardCertificateSecretRef
	if in.CACertificateSecretRef != nil {
		in, out := &in.CACertificateSecretRef, &out.CACertificateSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.ClusterIssuerRef != nil {
		in, out := &in.ClusterIssuerRef, &out.ClusterIssuerRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineIngress.
func (in *InlineIngress) DeepCopy() *InlineIngress {
	if in == nil {
		return nil
	}
	out := new(InlineIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlinePolicyEnforcement) DeepCopyInto(out *InlinePolicyEnforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlinePolicyEnforcement.
func (in *InlinePolicyEnforcement) DeepCopy() *InlinePolicyEnforcement {
	if in == nil {
		return nil
	}
	out := new(InlinePolicyEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoConfig) DeepCopyInto(out *KyvernoConfig) {
	*out = *in
	if in.Bundled != nil {
		in, out := &in.Bundled, &out.Bundled
		*out = new(BundledKyvernoConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoConfig.
func (in *KyvernoConfig) DeepCopy() *KyvernoConfig {
	if in == nil {
		return nil
	}
	out := new(KyvernoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretRef) DeepCopyInto(out *NamespacedSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretRef.
func (in *NamespacedSecretRef) DeepCopy() *NamespacedSecretRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalBlock) DeepCopyInto(out *OperationalBlock) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalBlock.
func (in *OperationalBlock) DeepCopy() *OperationalBlock {
	if in == nil {
		return nil
	}
	out := new(OperationalBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcement) DeepCopyInto(out *PolicyEnforcement) {
	*out = *in
	out.ClusterPolicy = in.ClusterPolicy
	out.WorkshopPolicy = in.WorkshopPolicy
	if in.Kyverno != nil {
		in, out := &in.Kyverno, &out.Kyverno
		*out = new(KyvernoConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcement.
func (in *PolicyEnforcement) DeepCopy() *PolicyEnforcement {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route53Config) DeepCopyInto(out *Route53Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route53Config.
func (in *Route53Config) DeepCopy() *Route53Config {
	if in == nil {
		return nil
	}
	out := new(Route53Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticCertificateConfig) DeepCopyInto(out *StaticCertificateConfig) {
	*out = *in
	out.TLSSecretRef = in.TLSSecretRef
	if in.CACertificateRef != nil {
		in, out := &in.CACertificateRef, &out.CACertificateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticCertificateConfig.
func (in *StaticCertificateConfig) DeepCopy() *StaticCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(StaticCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusIngress) DeepCopyInto(out *StatusIngress) {
	*out = *in
	out.WildcardCertificateSecretRef = in.WildcardCertificateSecretRef
	if in.CACertificateSecretRef != nil {
		in, out := &in.CACertificateSecretRef, &out.CACertificateSecretRef
		*out = new(NamespacedSecretRef)
		**out = **in
	}
	if in.ClusterIssuerRef != nil {
		in, out := &in.ClusterIssuerRef, &out.ClusterIssuerRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusIngress.
func (in *StatusIngress) DeepCopy() *StatusIngress {
	if in == nil {
		return nil
	}
	out := new(StatusIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPolicyEnforcement) DeepCopyInto(out *StatusPolicyEnforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPolicyEnforcement.
func (in *StatusPolicyEnforcement) DeepCopy() *StatusPolicyEnforcement {
	if in == nil {
		return nil
	}
	out := new(StatusPolicyEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopPolicyConfig) DeepCopyInto(out *WorkshopPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopPolicyConfig.
func (in *WorkshopPolicyConfig) DeepCopy() *WorkshopPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(WorkshopPolicyConfig)
	in.DeepCopyInto(out)
	return out
}
