apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/kyverno/upstream
    contents:
      - path: "."
        githubRelease:
          slug: kyverno/kyverno
          tag: v1.11.5
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
        includePaths:
          - install.yaml
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/kyverno-restricted/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "pod-security/restricted/**"
        excludePaths:
          - "**/kustomization.yaml"
          - "**/kyverno-test.yaml"
          - "**/0*.yaml"
          - "**/9*.yaml"
          - "**/pod*.yaml"
          - "**/resource.yaml"
          - "**/artifacthub-pkg.yml"
          - "**/.chainsaw-test"
          - "**/.kyverno-test"
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/kyverno-baseline/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "pod-security/baseline/**"
        excludePaths:
          - "**/kustomization.yaml"
          - "**/kyverno-test.yaml"
          - "**/0*.yaml"
          - "**/9*.yaml"
          - "**/pod*.yaml"
          - "**/resource.yaml"
          - "**/artifacthub-pkg.yml"
          - "**/.chainsaw-test"
          - "**/.kyverno-test"
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/kyverno-policies/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/kyverno/policies
          ref: origin/release-1.11
        includePaths:
          - "best-practices/disallow-empty-ingress-host/disallow-empty-ingress-host.yaml"
          - "best-practices/disallow-cri-sock-mount/disallow-cri-sock-mount.yaml"
          - "best-practices/restrict-service-external-ips/restrict-service-external-ips.yaml"
          - "best-practices/restrict-node-port/restrict-node-port.yaml"
          - "nginx-ingress/disallow-ingress-nginx-custom-snippets/disallow-ingress-nginx-custom-snippets.yaml"
          - "nginx-ingress/restrict-annotations/restrict-annotations.yaml"
          - "nginx-ingress/restrict-ingress-paths/restrict-ingress-paths.yaml"
          - "other/b-d/disallow-localhost-services/disallow-localhost-services.yaml"
          - "other/m-q/prevent-cr8escape/prevent-cr8escape.yaml"
          #! - "other/res/restrict-ingress-defaultbackend/restrict-ingress-defaultbackend.yaml"
          - "other/res/restrict-loadbalancer/restrict-loadbalancer.yaml"
          #! - "other/s-z/unique-ingress-host-and-path/unique-ingress-host-and-path.yaml"
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/cert-manager/upstream
    contents:
      - path: .
        githubRelease:
          slug: cert-manager/cert-manager
          tag: v1.14.7
          disableAutoChecksumValidation: true
        includePaths:
          - cert-manager.yaml
  #! Note that we download Contour twice, once for use in Educates package and
  #! once for use by the virtual clusters code in session-manager. Make sure the
  #! version is updated on both and operation of both use cases checked.
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/upstream
    contents:
      - path: .
        git:
          url: https://github.com/projectcontour/contour
          ref: v1.28.5
        newRootPath: examples/contour
  - path: session-manager/packages/contour/upstream
    contents:
      - path: .
        git:
          url: https://github.com/projectcontour/contour
          ref: v1.28.5
        newRootPath: examples/contour
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/external-dns/upstream
    contents:
      - path: .
        git:
          url: https://github.com/kubernetes-sigs/external-dns
          ref: v0.14.2
        includePaths:
          - kustomize/external-dns-*
        newRootPath: kustomize
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/kapp-controller/upstream
    contents:
      - path: .
        githubRelease:
          slug: carvel-dev/kapp-controller
          tag: v0.52.0
          disableAutoChecksumValidation: true
        includePaths:
          - release.yml
  - path: carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/lookup-service/upstream
    contents:
      - path: "."
        git:
          url: https://github.com/GrahamDumpleton/lab-platform-operator
          ref: origin/main
        includePaths:
          - exercises/resources/*.yaml
        newRootPath: exercises/resources
