#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager
  namespace: educates
  annotations:
    kapp.k14s.io/change-group.token: "educates-secrets/service-accounts-with-token"
    #! Following currently needed for kapp on OpenShift.
    #! TODO: Bring kapp rebaseRules for Openshift service accounts
#!    kapp.k14s.io/create-strategy: fallback-on-update
#!    kapp.k14s.io/update-strategy: skip
