---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-manager-token
  namespace: educates
  annotations:
    kubernetes.io/service-account.name: "secrets-manager"
    kapp.k14s.io/change-rule.token: "upsert after upserting educates-secrets/service-accounts-with-token"
#!    kapp.k14s.io/update-strategy: skip
type: kubernetes.io/service-account-token
