apiVersion: v1
kind: Secret
metadata:
  name: default-website-theme
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
{{- if .Values.websiteTheme }}
stringData:
  {{- range $k, $v := .Values.websiteTheme }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
