apiVersion: v1
kind: Secret
metadata:
  name: educates-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
stringData:
  educates-operator-config.yaml: |
    {{- include "session-manager.operatorConfigYAML" . | nindent 4 }}
  {{- $kyverno := include "session-manager.kyvernoPoliciesContent" . }}
  {{- if $kyverno }}
  kyverno-policies.yaml: |
    {{- $kyverno | nindent 4 }}
  {{- end }}
