apiVersion: v1
kind: Secret
metadata:
  name: default-website-theme
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
{{- $entries := include "session-manager.inlineThemeStringData" . | trim }}
{{- if and $entries (ne $entries "{}") }}
stringData:
  {{- $entries | nindent 2 }}
{{- end }}
