#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! We remove the policy which requires a seccompProfile be specified as it
#! is too restrictive and doesn't align well with how pod security policies
#! worked previously. We fallback instead on policy defined in baseline.

#@overlay/match by=overlay.subset({"kind":"ClusterPolicy", "metadata":{"name": "restrict-seccomp-strict"}})
#@overlay/remove
---
#@overlay/match by=overlay.subset({"kind":"ClusterPolicy"}),expects="1+"
---
metadata:
  #@overlay/replace via=lambda left, right: "educates-restricted-{}".format(left)
  name: null

#@overlay/match by=overlay.subset({"kind":"ClusterPolicy"}),expects="1+"
---
spec:
  rules:
    #@overlay/match by=overlay.all,expects="0+"
    - match:
        any:
          #@overlay/match by=overlay.all,expects="0+"
          - resources:
              #@overlay/match missing_ok=True
              namespaceSelector:
                matchExpressions:
                  - key: training.educates.dev/policy.engine
                    operator: In
                    values:
                      - kyverno
                  - key: training.educates.dev/policy.name
                    operator: In
                    values:
                      - restricted

#@overlay/match by=overlay.subset({"kind":"ClusterPolicy"}),expects="1+"
---
spec:
  validationFailureAction: Enforce
