---
kind: Namespace
apiVersion: v1
metadata:
  name: educates-installer
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: educates-installer
  namespace: educates-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: educates-installer
    namespace: educates-installer