---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lookup-service-access
  namespace: educates-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lookup-service-access
rules:
  - apiGroups:
      - training.educates.dev
    resources:
      - trainingportals
      - workshopenvironments
    verbs:
      - get
      - list
      - watch
    #! We need ability to watch for changes to CRDs so kopf can tell if its own
    #! custom resources have changed.
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lookup-service-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lookup-service-access
subjects:
  - kind: ServiceAccount
    name: lookup-service-access
    namespace: educates-platform
---
apiVersion: v1
kind: Secret
metadata:
  name: lookup-service-access
  namespace: educates-platform
  annotations:
    kubernetes.io/service-account.name: lookup-service-access
type: kubernetes.io/service-account-token
