#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.index(0)
      - image: #@ data.values.image.name
        imagePullPolicy: #@ data.values.image.pullPolicy