apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates:node-ca-injector
  labels:
    {{- include "node-ca-injector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates:node-ca-injector
subjects:
  - kind: ServiceAccount
    name: node-ca-injector
    namespace: {{ .Release.Namespace }}
