---
#! Cluster role for the lookup service application.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educates-lookup-service
rules:
  #! We need ability to watch for changes to CRDs so kopf can tell if its own
  #! custom resources have changed.
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  #! We need the ability to watch for namespace changes.
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
#! Cluster role for the remote access clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educates-remote-access
rules:
- apiGroups:
  - training.educates.dev
  resources:
  - trainingportals
  - workshopenvironments
  - workshopsessions
  - workshopallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
