#! Cluster role for the lookup service application.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educates-lookup-service-poc
rules:
  #! We need ability to watch for changes to CRDs so kopf can tell if its own
  #! custom resources have changed.
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  #! We need the ability to watch for namespace changes.
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
