apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigs.lookup.educates.dev
spec:
  scope: Namespaced
  group: lookup.educates.dev
  names:
    plural: clusterconfigs
    singular: clusterconfig
    kind: ClusterConfig
    categories:
      - educates-lookup
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Specification of the cluster configuration.
              properties:
                labels:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                credentials:
                  type: object
                  description: Credentials for the cluster.
                  required:
                    - kubeconfig
                  properties:
                    kubeconfig:
                      type: object
                      properties:
                        secretRef:
                          type: object
                          description: Reference to the secret containing the kubeconfig for the cluster.
                          required:
                            - name
                          properties:
                            name:
                              type: string
                              description: Name of the secret containing the kubeconfig for the cluster.
                            key:
                              type: string
                              description: Key in the secret containing the kubeconfig for the cluster.
                              default: config
                        context:
                          type: string
                          description: Context in the kubeconfig for the cluster.
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
