apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigurations.platform.educates.dev
spec:
  scope: Namespaced
  group: platform.educates.dev
  names:
    plural: clusterconfigurations
    singular: clusterconfiguration
    kind: ClusterConfiguration
    categories:
    - educates-platform
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Specification of the cluster configuration.
              required:
                - credentials
              properties:
                credentials:
                  type: object
                  description: Credentials for the cluster.
                  required:
                    - kubeconfigSecretRef
                  properties:
                    kubeconfigSecretRef:
                      type: object
                      description: Reference to the secret containing the kubeconfig for the cluster.
                      properties:
                        name:
                          type: string
                          description: Name of the secret containing the kubeconfig for the cluster.
                        key:
                          type: string
                          description: Key in the secret containing the kubeconfig for the cluster.
                          default: config
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
