#! Role for the lookup service application.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lookup-service
  namespace: educates
rules:
  #! We need read/write access to the ClusterConfig, ManagedCluster,
  #! ClientConfig and TenantConfig custom resources from the
  #! lookup.educates.dev API group.
  - apiGroups:
      - lookup.educates.dev
    resources:
      - clusterconfigs
      - managedclusters
      - clientconfigs
      - tenantconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  #! We need update access to the finalizers of the ClusterConfig,
  #! ManagedCluster, ClientConfig and TenantConfig custom resources from the
  #! lookup.educates.dev API group so kopf can track deletion.
  - apiGroups:
      - lookup.educates.dev
    resources:
      - clusterconfigs/finalizers
      - managedclusters/finalizers
      - clientconfigs/finalizers
      - tenantconfigs/finalizers
    verbs:
      - update
  #! We need read access to the secrets in the application namespace, so we can
  #! read the kubeconfig for the managed cluster.
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  #! We need the ability to create events in the application namespace so kopf
  #! can log events.
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
