apiVersion: v1
kind: Secret
metadata:
  name: remote-access-token
  namespace: educates
  annotations:
    kubernetes.io/service-account.name: remote-access
    kapp.k14s.io/change-rule: "upsert after upserting educates/sa-with-separate-token-secret"
type: kubernetes.io/service-account-token
