#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("functions.star", "xgetattr", "isClusterPackageEnableByDefault")
#@ load("educates.lib.yaml", "copy_all_educates_values")

#! This file contains default values for the custom infrastructure provider.
#! These are the values that will be set if not overridden by the user.

#@overlay/match-child-defaults missing_ok=True
#@overlay/replace
clusterPackages:
  contour:
    enabled: #@ isClusterPackageEnableByDefault("contour")
    settings:
      infraProvider: kind
      contour:
        replicas: 1
      configFileContents:
        defaultHttpVersions:
          - "HTTP/1.1"
      service:
        type: ClusterIP
        useHostPorts: true
  cert-manager:
    enabled: #@ isClusterPackageEnableByDefault("cert-manager")
    settings: {}
  external-dns:
    enabled: #@ isClusterPackageEnableByDefault("external-dns")
    settings: {}
  certs:
    enabled: #@ isClusterPackageEnableByDefault("certs")
    settings: {}
  kyverno:
    enabled: #@ isClusterPackageEnableByDefault("kyverno")
    settings: {}
  kapp-controller:
    enabled: #@ isClusterPackageEnableByDefault("kapp-controller")
    settings: {}
  educates:
    enabled: #@ isClusterPackageEnableByDefault("educates")
    settings: #@ xgetattr(data.values, "clusterPackages.educates.settings")
  lookup-service:
    enabled: #@ isClusterPackageEnableByDefault("lookup-service")
    settings:
#!      namespace:
#!        create: True
      clusterIngress:
        domain: #@ data.values.clusterIngress.domain
