#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:assert", "assert")
#@ load("/functions.star", "isGlobalCaCertificateRefEnabled", "xgetattr")

#! This file is used to set the default values for the vcluster installation
#! Add to this file all the defaults that you don't want to be overidden by the user
#! These values will override all the values provided by the user either in the global configuration
#! or the clusterPackages.educates configuration

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  #@ if/end not hasattr(data.values, "clusterPackages") or not hasattr(data.values.clusterPackages, "contour") or not hasattr(data.values.clusterPackages.contour, "enabled") or not data.values.clusterPackages.contour.enabled == False:
  contour:
    settings:
      infraProvider: kind
      contour:
        replicas: 1
      configFileContents:
        defaultHttpVersions:
          - "HTTP/1.1"
      service:
        type: ClusterIP
        useHostPorts: true
  #@ if/end hasattr(data.values, "clusterPackages") and hasattr(data.values.clusterPackages, "lookup-service") and hasattr(data.values.clusterPackages["lookup-service"], "enabled") and data.values.clusterPackages["lookup-service"].enabled == True:
  lookup-service:
    settings:
#!      namespace:
#!        create: True
      clusterIngress:
        domain: #@ data.values.clusterIngress.domain
