//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAccessCredentials) DeepCopyInto(out *DefaultAccessCredentials) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAccessCredentials.
func (in *DefaultAccessCredentials) DeepCopy() *DefaultAccessCredentials {
	if in == nil {
		return nil
	}
	out := new(DefaultAccessCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageOverride) DeepCopyInto(out *ImageOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageOverride.
func (in *ImageOverride) DeepCopy() *ImageOverride {
	if in == nil {
		return nil
	}
	out := new(ImageOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePrePuller) DeepCopyInto(out *ImagePrePuller) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePrePuller.
func (in *ImagePrePuller) DeepCopy() *ImagePrePuller {
	if in == nil {
		return nil
	}
	out := new(ImagePrePuller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRef) DeepCopyInto(out *ImageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRef.
func (in *ImageRef) DeepCopy() *ImageRef {
	if in == nil {
		return nil
	}
	out := new(ImageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]ImageOverride, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressOverrides) DeepCopyInto(out *IngressOverrides) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.CACertificateSecretRef != nil {
		in, out := &in.CACertificateSecretRef, &out.CACertificateSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressOverrides.
func (in *IngressOverrides) DeepCopy() *IngressOverrides {
	if in == nil {
		return nil
	}
	out := new(IngressOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupService) DeepCopyInto(out *LookupService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupService.
func (in *LookupService) DeepCopy() *LookupService {
	if in == nil {
		return nil
	}
	out := new(LookupService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LookupService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupServiceIngress) DeepCopyInto(out *LookupServiceIngress) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupServiceIngress.
func (in *LookupServiceIngress) DeepCopy() *LookupServiceIngress {
	if in == nil {
		return nil
	}
	out := new(LookupServiceIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupServiceList) DeepCopyInto(out *LookupServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LookupService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupServiceList.
func (in *LookupServiceList) DeepCopy() *LookupServiceList {
	if in == nil {
		return nil
	}
	out := new(LookupServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LookupServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupServiceSpec) DeepCopyInto(out *LookupServiceSpec) {
	*out = *in
	in.Ingress.DeepCopyInto(&out.Ingress)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageRef)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupServiceSpec.
func (in *LookupServiceSpec) DeepCopy() *LookupServiceSpec {
	if in == nil {
		return nil
	}
	out := new(LookupServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupServiceStatus) DeepCopyInto(out *LookupServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupServiceStatus.
func (in *LookupServiceStatus) DeepCopy() *LookupServiceStatus {
	if in == nil {
		return nil
	}
	out := new(LookupServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCATrust) DeepCopyInto(out *NodeCATrust) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCATrust.
func (in *NodeCATrust) DeepCopy() *NodeCATrust {
	if in == nil {
		return nil
	}
	out := new(NodeCATrust)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryMirror) DeepCopyInto(out *RegistryMirror) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryMirror.
func (in *RegistryMirror) DeepCopy() *RegistryMirror {
	if in == nil {
		return nil
	}
	out := new(RegistryMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteAccess) DeepCopyInto(out *RemoteAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteAccess.
func (in *RemoteAccess) DeepCopy() *RemoteAccess {
	if in == nil {
		return nil
	}
	out := new(RemoteAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManager) DeepCopyInto(out *SecretsManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManager.
func (in *SecretsManager) DeepCopy() *SecretsManager {
	if in == nil {
		return nil
	}
	out := new(SecretsManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerList) DeepCopyInto(out *SecretsManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretsManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerList.
func (in *SecretsManagerList) DeepCopy() *SecretsManagerList {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerSpec) DeepCopyInto(out *SecretsManagerSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageRef)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerSpec.
func (in *SecretsManagerSpec) DeepCopy() *SecretsManagerSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerStatus) DeepCopyInto(out *SecretsManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerStatus.
func (in *SecretsManagerStatus) DeepCopy() *SecretsManagerStatus {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionManager) DeepCopyInto(out *SessionManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionManager.
func (in *SessionManager) DeepCopy() *SessionManager {
	if in == nil {
		return nil
	}
	out := new(SessionManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SessionManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionManagerList) DeepCopyInto(out *SessionManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SessionManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionManagerList.
func (in *SessionManagerList) DeepCopy() *SessionManagerList {
	if in == nil {
		return nil
	}
	out := new(SessionManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SessionManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionManagerSpec) DeepCopyInto(out *SessionManagerSpec) {
	*out = *in
	if in.IngressOverrides != nil {
		in, out := &in.IngressOverrides, &out.IngressOverrides
		*out = new(IngressOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkshopPolicyOverride != nil {
		in, out := &in.WorkshopPolicyOverride, &out.WorkshopPolicyOverride
		*out = new(WorkshopPolicyOverride)
		**out = **in
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(Images)
		(*in).DeepCopyInto(*out)
	}
	if in.Themes != nil {
		in, out := &in.Themes, &out.Themes
		*out = make([]Theme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tracking != nil {
		in, out := &in.Tracking, &out.Tracking
		*out = new(Tracking)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultAccessCredentials != nil {
		in, out := &in.DefaultAccessCredentials, &out.DefaultAccessCredentials
		*out = new(DefaultAccessCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedEmbeddingHosts != nil {
		in, out := &in.AllowedEmbeddingHosts, &out.AllowedEmbeddingHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(SessionStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SessionNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePrePuller != nil {
		in, out := &in.ImagePrePuller, &out.ImagePrePuller
		*out = new(ImagePrePuller)
		**out = **in
	}
	if in.RegistryMirrors != nil {
		in, out := &in.RegistryMirrors, &out.RegistryMirrors
		*out = make([]RegistryMirror, len(*in))
		copy(*out, *in)
	}
	if in.NodeCATrust != nil {
		in, out := &in.NodeCATrust, &out.NodeCATrust
		*out = new(NodeCATrust)
		**out = **in
	}
	if in.RemoteAccess != nil {
		in, out := &in.RemoteAccess, &out.RemoteAccess
		*out = new(RemoteAccess)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionManagerSpec.
func (in *SessionManagerSpec) DeepCopy() *SessionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(SessionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionManagerStatus) DeepCopyInto(out *SessionManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(NamespacedRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionManagerStatus.
func (in *SessionManagerStatus) DeepCopy() *SessionManagerStatus {
	if in == nil {
		return nil
	}
	out := new(SessionManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionNetwork) DeepCopyInto(out *SessionNetwork) {
	*out = *in
	if in.PacketSize != nil {
		in, out := &in.PacketSize, &out.PacketSize
		*out = new(int32)
		**out = **in
	}
	if in.BlockedCIDRs != nil {
		in, out := &in.BlockedCIDRs, &out.BlockedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionNetwork.
func (in *SessionNetwork) DeepCopy() *SessionNetwork {
	if in == nil {
		return nil
	}
	out := new(SessionNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStorage) DeepCopyInto(out *SessionStorage) {
	*out = *in
	if in.StorageGroup != nil {
		in, out := &in.StorageGroup, &out.StorageGroup
		*out = new(int64)
		**out = **in
	}
	if in.StorageUser != nil {
		in, out := &in.StorageUser, &out.StorageUser
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionStorage.
func (in *SessionStorage) DeepCopy() *SessionStorage {
	if in == nil {
		return nil
	}
	out := new(SessionStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Theme) DeepCopyInto(out *Theme) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Theme.
func (in *Theme) DeepCopy() *Theme {
	if in == nil {
		return nil
	}
	out := new(Theme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThemeSource) DeepCopyInto(out *ThemeSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThemeSource.
func (in *ThemeSource) DeepCopy() *ThemeSource {
	if in == nil {
		return nil
	}
	out := new(ThemeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracking) DeepCopyInto(out *Tracking) {
	*out = *in
	if in.GoogleAnalytics != nil {
		in, out := &in.GoogleAnalytics, &out.GoogleAnalytics
		*out = new(TrackingProvider)
		**out = **in
	}
	if in.Amplitude != nil {
		in, out := &in.Amplitude, &out.Amplitude
		*out = new(TrackingProvider)
		**out = **in
	}
	if in.Clarity != nil {
		in, out := &in.Clarity, &out.Clarity
		*out = new(TrackingProvider)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(TrackingWebhook)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracking.
func (in *Tracking) DeepCopy() *Tracking {
	if in == nil {
		return nil
	}
	out := new(Tracking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingProvider) DeepCopyInto(out *TrackingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingProvider.
func (in *TrackingProvider) DeepCopy() *TrackingProvider {
	if in == nil {
		return nil
	}
	out := new(TrackingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingWebhook) DeepCopyInto(out *TrackingWebhook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingWebhook.
func (in *TrackingWebhook) DeepCopy() *TrackingWebhook {
	if in == nil {
		return nil
	}
	out := new(TrackingWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkshopPolicyOverride) DeepCopyInto(out *WorkshopPolicyOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkshopPolicyOverride.
func (in *WorkshopPolicyOverride) DeepCopy() *WorkshopPolicyOverride {
	if in == nil {
		return nil
	}
	out := new(WorkshopPolicyOverride)
	in.DeepCopyInto(out)
	return out
}
