#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match-child-defaults missing_ok=True
#@overlay/replace
clusterPackages:
  contour:
    enabled: false
    settings: {}
  cert-manager:
    enabled: false
    settings: {}
  external-dns:
    enabled: false
    settings: {}
  certs:
    enabled: false
    settings: {}
  kyverno:
    enabled: false
    settings: {}
  kapp-controller:
    enabled: false
    settings: {}
  educates:
    enabled: false
    settings: {}
  lookup-service:
    enabled: false
    settings: {}