#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  lookup-service:
    #@ if/end hasattr(data.values, "clusterPackages") and hasattr(data.values.clusterPackages, "lookup-service") and hasattr(data.values.clusterPackages["lookup-service"], "enabled") and data.values.clusterPackages["lookup-service"].enabled == True:
    settings:
      clusterIngress:
        domain: #@ data.values.clusterIngress.domain
        clusterIssuer: educateswildcard
