#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Namespace
metadata:
  name: educates
  #@ if data.values.clusterSecurity.policyEngine == "pod-security-standards":
  labels:
    pod-security.kubernetes.io/enforce: baseline
  #@ end
