#@ load("@ytt:data", "data")

#@ ingress_ca_secret = data.values.clusterIngress.caCertificateRef.name
#@ if not ingress_ca_secret and getattr(data.values.clusterIngress.caCertificate, "ca.crt"):
#@ ingress_ca_secret = "{}-ca".format(data.values.clusterIngress.domain)
#@ end

#@ if ingress_ca_secret and data.values.clusterIngress.caNodeInjector.enabled:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-injector
  namespace: educates
data:
  inject-ca.sh: |
    echo "$CA_CERTIFICATE" > /usr/local/share/ca-certificates/Cluster_Ingress_CA.crt && update-ca-certificates && systemctl restart containerd
#@ end
