clusterInfrastructure:
  provider: "vcluster"
clusterPackages:
  educates:
    settings:
      imagePuller:
        enabled: true
        prePullImages:
        - "a"
  lookup-service:
    enabled: true
imagePuller:
  enabled: true
  prePullImages:
  - "b"
workshopSecurity:
  rulesEngine: "none"
workshopAnalytics:
  google:
    trackingId: "analytics"
clusterIngress:
  domain: "educates.example.com"
