#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:md5", "md5")
#@ load("/00-package.star", "image_reference", "image_pull_policy")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager
  namespace: educates
  annotations:
    kapp.k14s.io/change-rule.token: "upsert after upserting educates-sessions/service-accounts-with-token"
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: session-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: session-manager
    spec:
      serviceAccountName: session-manager
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        #! seccompProfile:
        #!   type: RuntimeDefault
      containers:
      - name: operator
        #@ image = image_reference("session-manager")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        startupProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 4
          httpGet:
            path: /healthz?probe=startup
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz?probe=liveness
            port: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/app-root/config/
        - name: token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: educates-config
      - name: token
        secret:
          secretName: session-manager-token
