#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_pull_secrets")

#@ pull_secrets = image_pull_secrets()
#@ if pull_secrets:
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretInjector
metadata:
  name: educates-image-pull-secrets
spec:
  rules:
  - targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: portal
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          training.educates.dev/component: portal
  - targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          training.educates.dev/component: environment
  - targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          training.educates.dev/component: session
#@ end

---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretInjector
metadata:
  name: educates-registry-credentials
spec:
  rules:
  - targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: session
    sourceSecrets:
      nameSelector:
        matchNames:
        - educates-registry-credentials
    serviceAccounts:
      nameSelector:
        matchNames:
        - default
